### ISSUE TITLE
Pluralsight javaScript sample website missing

### ISSUE THREAD

**Issue by herlydev** [pluralsight/web-dev-starter#1]
I decided to try the free weekend Pluralsight weekend. I am interested on learning JavaScript, however while following the video Pluralsight javaScript sample website looks like the folder is correct for the whole "Craved rock fitness" is missing. FYI, without this folder, the whole video series is hard to follow.

**Comment by Sidegit-sudo** [comment]
^ I second that

**Comment by JonathanStauffer** [comment]
![exerciseFiles](https://user-images.githubusercontent.com/34604092/74154424-a159dd00-4be0-11ea-8846-808476a2f023.png)
The exercise files for "Carved Rock" are not located within Github, rather they are housed in PluralSight. By clicking the lesson in PluralSight and clicking on the tab for "Exercise files" you can download them. See the attached screenshot. Hope this helps! I had a little difficulty locating them at first as well.

**Comment by AishuKS** [comment]
I downloaded the files but still i couldn't find the file names described as per the video "Introduction to javascript - Our sample website". The index.html file itself is not available. 
Please someone help me with this. 
Thanks in advance.

**Comment by amansresta** [comment]
Good one bro

**Comment by amansresta** [comment]
> ![exerciseFiles](https://user-images.githubusercontent.com/34604092/74154424-a159dd00-4be0-11ea-8846-808476a2f023.png)
> The exercise files for "Carved Rock" are not located within Github, rather they are housed in PluralSight. By clicking the lesson in PluralSight and clicking on the tab for "Exercise files" you can download them. See the attached screenshot. Hope this helps! I had a little difficulty locating them at first as well.

Good one bro

**Comment by jimibluesman** [comment]
Same thing happened to me...found the files at the same place as @amansresta and then had to console my software developer friend on how to actually get it to run...basically, you need to add the javascript-getting-started.zip file to the git folder and re-installed npm...then ran it

**Comment by madhusrhd** [comment]
How do I contact the instructor of this course?

**Comment by menezesmario** [comment]
the files on the sample site don't have folder 1? starts in folder 2?

**Comment by rezak1989** [comment]
It took me few hours to realize that I need to download the files from Pluralsight. This is different than what you teach on your videos and you need to correct your video. You are wasting our time.

**Comment by dellannie** [comment]
Long story short I run into the same problem. Sitting here for about an hr trying to figure out how to get the files.

**Comment by CharlyfromVianden** [comment]
> Same thing happened to me...found the files at the same place as @amansresta and then had to console my software developer friend on how to actually get it to run...basically, you need to add the javascript-getting-started.zip file to the git folder and re-installed npm...then ran it

And how can I do that without a resource of friends who know how to code? :)

**Comment by fseyoum11** [comment]
Same thing in here but thank you for the guy who post the question. For future, please be specific as much as possible. Thank You.

**Comment by amansresta** [comment]
Please go to the course tab and click on exercise file tab. There you can
download your exercise files.
Thank you

**Comment by herlydev** [comment]
Thank you for providing a solution/ work around.

**Comment by yellowjello009** [comment]
I downloaded exercise file files but didn't find the project

**Comment by SebMace** [comment]
There's no content in exercice file ! 
![2020-04-16 07_43_41-Window](https://user-images.githubusercontent.com/12663948/79419022-3f3d9f80-7fb6-11ea-9b54-8fb73e4eb930.png)

**Comment by Bendram** [comment]
> It took me a few hours to realize that I need to download the files from Pluralsight. This is different than what you thought on your course and you need to correct your video/slide. You are wasting our time.

Be respectful. He is doing us a favor by teaching us in a simplest way. You can ask him to include your suggestions in to the video/slide nicely.

**Comment by SebMace** [comment]
Hello Bedram, 
Sorry if I was rude, I apologize. 
But I was really upset to be unable to find these files because the course seemed to me very interesting.
All apologize again.
Sincerely yours.
Sébastien

**Comment by rkgits** [comment]
> > It took me a few hours to realize that I need to download the files from Pluralsight. This is different than what you thought on your course and you need to correct your video/slide. You are wasting our time.
> 
> Be respectful. He is doing us a favor by teaching us in a simplest way. You can ask him to include your suggestions in to the video/slide nicely.

Pluralsight a public company (NYSE: PS) and it's a paid e-learning platform and this is an issue within their content. This is a world-class business and we have tried to inform them about this issue. I, personally have reached out to Pluralsight Support team to notify them about the issue but I have not heard back from them. As you see, this issue happened to so many users and it's really wasting people's time and I believe it's more respectful to our time (and money) to fix this issue and respond to the support ticket that customers raised. 
Simply we are paying to receive quality content and it's a business not a personal favor.

**Comment by madhusrhd** [comment]
Why I am getting these feedback emails? I didn’t make that comment.

Thanks,
Madhu

**Comment by Florian-Voss** [comment]
honestly guys whoever ran into this problem of wasting "hours" to find the file should think a second time about becoming a programmer. I mean there was only one source given, which is the git repository. So if it's not in there, you might wanna checkout the course on pluralsight if there are any extra sources... Isn't that just logical thinking? I do agree that there should have been a reference to that, as you can see I was indeed searching for the issue myself. But it took me 2 minutes to solve and to all the people that wasted "hours", I am just speechless. Even if I end up not being able to fix the issue, i can't picture myself sitting there for 3 hours, waiting for a solution :D just go ahead to the next thing that you think you're able to do! instead of wasting time and then blaming someone else for the time that YOU spent for nothing. You might for example continue the course focusing on the theory, instead of repeating every step he does yourself. Or even pick a different course from another website. It sounds more like you took it as a welcome chance not to work. While telling yourself that it's some random person's fault. I think that's the maximum of rudeness. He tries to teach us stuff and tbh i couldnt find better videos than what pluralsight offers. Instead of thanking them, you even blame them for wasting your time. They did not make you do anything. Neither watch the video in the first place, nor pausing it and sitting there for hours. All they did was offering awesome courses and you were just unable to use them. But as you found out now, it was not an unsolvable issue presented by them, but your own incapability of finding it.

**Comment by derekowusubekoe** [comment]
> Same thing happened to me...found the files at the same place as @amansresta and then had to console my software developer friend on how to actually get it to run...basically, you need to add the javascript-getting-started.zip file to the git folder and re-installed npm...then ran it

Can you provide the steps because I did go through the steps but I am getting an error below;

> npm install
npm WARN saveError ENOENT: no such file or directory, open '/Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json'
npm WARN javascript-getting-started No description
npm WARN javascript-getting-started No repository field.
npm WARN javascript-getting-started No README data
npm WARN javascript-getting-started No license field.

up to date in 0.591s
found 0 vulnerabilities

> npm run start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by zobmaniac** [comment]
> > Same thing happened to me...found the files at the same place as @amansresta and then had to console my software developer friend on how to actually get it to run...basically, you need to add the javascript-getting-started.zip file to the git folder and re-installed npm...then ran it
> 
> Can you provide the steps because I did go through the steps but I am getting an error below;
> 
> > npm install
> > npm WARN saveError ENOENT: no such file or directory, open '/Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json'
> > npm WARN enoent ENOENT: no such file or directory, open '/Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json'
> > npm WARN javascript-getting-started No description
> > npm WARN javascript-getting-started No repository field.
> > npm WARN javascript-getting-started No README data
> > npm WARN javascript-getting-started No license field.
> 
> up to date in 0.591s
> found 0 vulnerabilities
> 
> > npm run start
> > npm ERR! code ENOENT
> > npm ERR! syscall open
> > npm ERR! path /Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json
> > npm ERR! errno -2
> > npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/mac_ext_mem/programming/javascript/javascript-getting-started/package.json'
> > npm ERR! enoent This is related to npm not being able to find a file.
> >

Did you find a solution?

**Comment by karthikeyan-cs** [comment]
Guys use the below link to access the content.

https://github.com/carved-rock-fitness/carved-rock-fitness-webapp

It hardly took me few minutes to figure it out. Try google in different ways, you will find a solution one way or other.

**Comment by Jober1** [comment]
![image](https://user-images.githubusercontent.com/105317615/168151668-3c974240-0b9f-4d11-a56f-1eab8a27213d.png)
no file?
